### PR TITLE
Update fflas-ffpack

### PR DESCRIPTION
**Pull request by mahrud**
@DanGrayson you should probably make a PR to submit your changes from https://github.com/Macaulay2/fflas-ffpack/tree/add-const-tags to upstream. I don't know why they were needed, so I can't make the PR.

### CODE REVIEW

**Comment by DanGrayson** [comment]
> @DanGrayson you should probably make a PR to submit your changes from https://github.com/Macaulay2/fflas-ffpack/tree/add-const-tags to upstream. I don't know why they were needed, so I can't make the PR.

Good idea.   But we seem to be doing without the patch, so I'll wait until I run into again, so I can tell them on what system the change is required.

**Comment by mahrud** [comment]
No, we've been using the patch.

**Comment by mahrud** [comment]
It wasn't on master, but the commit in M2 included the patch.

**Comment by DanGrayson** [comment]
> No, we've been using the patch.

I think not.  See https://github.com/Macaulay2/M2/blob/a24290888d57453b8365ae1bb703b1e5173bae9d/.gitmodules#L27

**Comment by mahrud** [comment]
> > No, we've been using the patch.
> 
> I think not. See https://github.com/Macaulay2/M2/blob/a24290888d57453b8365ae1bb703b1e5173bae9d/.gitmodules#L27

Please, do think:
https://github.com/Macaulay2/M2/tree/development/M2/submodules
https://github.com/linbox-team/fflas-ffpack/tree/91ca323d0dfe2236148a2847d33602fc702f2a8f

**Comment by DanGrayson** [comment]
So my patch is upstream, but not on a branch.  How did that happen?

**Comment by mahrud** [comment]
> So my patch is upstream, but not on a branch. How did that happen?

It's not in the upstream. This is a feature/bug of github, that all forks of the same repository are connected behind the scenes, so if you take a commit that belongs to a fork, and ask for that commit form the main repository, you won't get an error.

**Comment by DanGrayson** [comment]
> > So my patch is upstream, but not on a branch. How did that happen?
> 
> It's not in the upstream. This is a feature/bug of github, that all forks of the same repository are connected behind the scenes, so if you take a commit that belongs to a fork, and ask for that commit form the main repository, you won't get an error.

Aargh.  That's deceptive on github's part.

**Comment by mahrud** [comment]
> Aargh. That's deceptive on github's part.

I think not. It's not efficient to keep multiple copies of the same commit, so might as well store all commits in one place. After all, it's all in one server.

A related caveat: a single user can't have multiple forks of the same repository.

**Comment by DanGrayson** [comment]
> > Aargh. That's deceptive on github's part.
> 
> I think not. It's not efficient to keep multiple copies of the same commit, so might as well store all commits in one place. After all, it's all in one server.
> 

Certainly they could achieve the efficiency of storing just one copy of each commit without the deception of users' repositories appearing to be the same.

**Comment by DanGrayson** [comment]
We should stop using that misfeature of github's.

**Comment by mahrud** [comment]
Can this be merged now? Then I can put the Macaulay2 repository in the brew bottle instead of mine.

**Pull request merged**
