### PR TITLE
take OMPFLAGS from environment

### PR DESCRIPTION
**Pull request by mahrud**
See https://github.com/linbox-team/fflas-ffpack/issues/309

### CODE REVIEW

**Comment by DanGrayson** [comment]
Looks good but this should be directed to our patches branch, not the master branch, which should agree with what's upstream.

**Comment by mahrud** [comment]
> Looks good but this should be directed to our patches branch, not the master branch, which should agree with what's upstream.

The head of Macaulay2-patch is 3.5 years old and master is 15 days old, so master already doesn't agree with the upstream.

Nobody is going to build fflas--ffpack from the master branch on _our_ fork, so I don't get your rule. Your decisions on how to manage git repositories seem very inconsistent to me and sometimes change arbitrarily every other week, so feel free to do whatever you need to do.

**Comment by DanGrayson** [comment]
> Your decisions on how to manage git repositories seem very inconsistent to me and sometimes change arbitrarily every other week,


Well, that's not the intention.  Could you point out an inconsistency to me so we can repair it?

**Comment by DanGrayson** [comment]
You're right that I've modified the master branch on this repository : once myself in July, and a few weeks ago by pulling a pull request of yours.  And that is inconsistent with what I've done on other repositories.  So I'll pull this and we can think about that later.

**Pull request merged**
